[versions]
kotlin = "1.8.22"
coroutines = "1.8.1"
gson = "2.10.1"
junit = "4.13.2"
truth = "1.4.2"
mockito = "5.11.0"
mockito-kotlin = "5.1.0"

[libraries]
# Kotlin
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

# Serialization
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
